/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jag.gui;

/**
 *
 * @author matt
 */
public class ScreenLanguageSintax extends javax.swing.JFrame {

    /**
     * Creates new form ScreenLanguageSintax
     */
    public ScreenLanguageSintax() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tittleScreen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_sintax = new javax.swing.JTextArea();
        jLabel_text01 = new javax.swing.JLabel();
        jLabel_text02 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_example = new javax.swing.JTextArea();
        jButton_mainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_tittleScreen.setFont(new java.awt.Font("Umpush", 3, 48)); // NOI18N
        jLabel_tittleScreen.setText("Jaguar Compiler");

        jTextArea_sintax.setColumns(20);
        jTextArea_sintax.setRows(5);
        jTextArea_sintax.setText("SINTAXE:\n\n - Função:\n\nfunction tipoDaFuncao nomeDaFuncao() {}\n\n - If:\n\nif(expressaoLogica) {}\nif(expressaoLogica) {}elif(expressaoLogica) {}\nif(expressaoLogica) {}elif(expressaoLogica) {}else {}\nif(expressaoLogica) {}else {}\n\n - While:\n\nwhile(expressaoLogica) {}\n\n - For:\n\nfor(tipoVariavel nomeVariavel in valorParada) {}\nfor(nomeVariavelJaCriada in valorParada) {}\n\n - Declaração de Variáveis:\n\ntipoVariavel nomeVariavel\ntipoVariavel nomeVariavel = valorInicial\n\n - Tipos para Variáveis:\n\nreal (Valores ponto flutuante)\nint (Valores inteiros)\nbool (Valores booleanos)\ncharac (Um caracter)\nstr (Uma string)\n\n - Apresentar no console:\n\nprint(informacaoParaApresentar)\n\n - Entrada de dados no programa:\n\ninput()\nEx: str nome = input()\n\n - Operações booleanas:\n\nand (as duas expressões lógicas precisam ser verdade)\nor (as duas ou apenas uma expressão lógica precisa ser verdade)");
        jScrollPane1.setViewportView(jTextArea_sintax);

        jLabel_text01.setFont(new java.awt.Font("Umpush", 0, 12)); // NOI18N
        jLabel_text01.setText("Language Sintax:");

        jLabel_text02.setFont(new java.awt.Font("Umpush", 0, 12)); // NOI18N
        jLabel_text02.setText("Language Example:");

        jTextArea_example.setColumns(20);
        jTextArea_example.setRows(5);
        jTextArea_example.setText("function void main(){\n\tif(x){\n\t\tfor(int x in colors){\n\t\t\tint a\n\t\t\tstr nome = \"Mathias\"\n\t\t\tprint(nome)\n\t\t\tnome = input()\n\t\t}\n\t}elif(x<y){\n\t\tprint(\"oloko\")\n\t}else{\n\t\tprint(\"jpb\")\n\t}\n\n\twhile(x<y){\n\t\tprint(\"hello world\")\n\t}\n}");
        jScrollPane2.setViewportView(jTextArea_example);

        jButton_mainMenu.setFont(new java.awt.Font("Umpush", 0, 12)); // NOI18N
        jButton_mainMenu.setText("Main Menu");
        jButton_mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_tittleScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_text01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_text02)
                        .addGap(255, 255, 255))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_tittleScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_text01)
                    .addComponent(jLabel_text02))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_mainMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mainMenuActionPerformed
        ScreenMain screenMain = new ScreenMain();
        screenMain.setLocationRelativeTo(null);
        screenMain.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_mainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenLanguageSintax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenLanguageSintax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenLanguageSintax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenLanguageSintax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenLanguageSintax().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_mainMenu;
    private javax.swing.JLabel jLabel_text01;
    private javax.swing.JLabel jLabel_text02;
    private javax.swing.JLabel jLabel_tittleScreen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_example;
    private javax.swing.JTextArea jTextArea_sintax;
    // End of variables declaration//GEN-END:variables
}
