
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 27 16:00:14 BRT 2019
//----------------------------------------------------

package com.jag.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_ADICAO = 3;
  public static final int error = 1;
  public static final int CONSTANTE = 2;
  public static final int EOF = 0;
  public static final int OP_SUB = 4;
}

