
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 30 14:49:44 BRT 2019
//----------------------------------------------------

package com.jag.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FECHAR_BLOCO = 7;
  public static final int STRING_CHARAC_VAZIA = 15;
  public static final int STRING_VAZIA = 13;
  public static final int FUNCTION = 27;
  public static final int STR = 25;
  public static final int FECHAR_PAR = 4;
  public static final int CHARAC = 23;
  public static final int INPUT = 44;
  public static final int OP_MAIORIGUAL = 11;
  public static final int OP_SUBTRACAO = 35;
  public static final int OP_NOT = 18;
  public static final int INT = 20;
  public static final int FOR = 39;
  public static final int OP_ADICAO = 34;
  public static final int ABRIR_BLOCO = 6;
  public static final int VIRGULA = 28;
  public static final int PONTO = 31;
  public static final int OP_DIV = 36;
  public static final int OP_MENORIGUAL = 16;
  public static final int CONSTANTE = 33;
  public static final int IDENTIFICADOR = 5;
  public static final int IN = 40;
  public static final int BOOL = 22;
  public static final int OP_E = 9;
  public static final int IF = 2;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int TRUE = 29;
  public static final int error = 1;
  public static final int OP_OU = 19;
  public static final int OP_MULT = 37;
  public static final int STRING_CHARAC = 14;
  public static final int VOID = 24;
  public static final int REAL = 21;
  public static final int ELSE = 41;
  public static final int OP_COMPARACAO = 17;
  public static final int WHILE = 38;
  public static final int OP_ATRIBUICAO = 32;
  public static final int STRING = 12;
  public static final int FALSE = 30;
  public static final int OP_MAIOR = 10;
  public static final int ABRIR_PAR = 3;
  public static final int ELIF = 42;
  public static final int PRINT = 43;
  public static final int OP_MENOR = 8;
}

